### ISSUE TITLE
Add fuzzing blockhashes for testing on CI

### ISSUE THREAD

**Issue by afalaleev** [neonlabsorg/python-logged-groups#6]
For better Proxy testing on CI stands before running on the Solana devnet/testnet. 
This allow to find errors before running version on the public clusters

**Comment by afalaleev** [comment]
Depends on upgrading of Solana to 1.8.12

**Comment by vasiliy-zaznobin** [comment]
Issue moved to [neonlabsorg/proxy-model.py #495](https://github.com/neonlabsorg/proxy-model.py/issues/495) via [**ZenHub**](https://www.zenhub.com/)
